### PR TITLE
bugfix/correct behavior for variables with name text

### PR DESCRIPTION
**Pull request by xalanq**
`text` is really common and it should not be a temporary value's name.

E.g.

in csv

```
test,for testing %text$s
```

plugin will generate the codes like

```
static String test({
    @required String text,
  }) {
    String text = getText("test");
    if (text != null) {
      text = text.replaceAll("%text\$s", text);
    }
    return text;
  }
```

It will get a wrong string `for testing for testing %text$s` when call the `test` method

### CODE REVIEW

**Comment by defuncart** [comment]
Hi @xalanq, thanks for using flappy_translator, spotting this issue and opening a PR! I will take a look tomorrow, seems like a good improvement :)

**Comment by defuncart** [comment]
Hi @xalanq. Can you run 'flutter pub run flappy_translator` in example folder and push `i18n.dart`? Then PR will be ready to be merged 🥳  You may need to pull upstream master into your fork as I just updated the example project to be compatible with newer versions of flutter.

**Comment by xalanq** [comment]
Sorry for the late reply. I've merged the upstream/master and generated `i18n.dart`, plz check it!

**Comment by defuncart** [comment]
@xalanq Once again thank you very much for your contribution. This fix will be part of version 1.5.0 which I hope to release over the weekend/next week.

**Pull request merged**
