### PR TITLE
Update to support latest dependencies versions

### PR DESCRIPTION
**Pull request by Carapacik**

### CODE REVIEW

**Comment by Carapacik** [comment]
Problem with archive versions in excel
https://github.com/justkawal/excel/issues/364

**Comment by defuncart** [comment]
@Carapacik Thanks for the contribution. I will review in a few days once I've pushed some parsing fixes to master.

**Comment by Carapacik** [comment]
@defuncart issue fixed

**Comment by Carapacik** [comment]
@defuncart

**Comment by defuncart** [comment]
@Carapacik Thank you for opening this PR. Min dart sdk has been update to 3.0.0 in #63, while in #64 excel has been updated to 3.0.0: version 4.0.0 is not possible due to XML constraint issue (https://github.com/justkawal/excel/pull/376). Closing this PR as it is no longer required. flappy_translator version 2.1.0 will be released shortly. Thanks again for raising this issue.

**Pull request closed without merging**
